django/05_django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

django/05_django/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',) # first_name, last_name

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')

django/05_django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 로그인
            auth_login(request, form.get_user())
            result = request.GET.get('next')
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    # 로그아웃
    auth_logout(request)
    return redirect('articles:index')


# create와 동일
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # 회원가입 후 로그인
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def delete(request):
    request.user.delete()
    # auth_logout(request) # 필수는 아님, 순서는 중요
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request,'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

django/05_django/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
	<h1>비밀번호변경</h1>
	<form action="{% url 'accounts:change_password' %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>
{% endblock content %}

django/05_django/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
	<h1>LOGIN</h1>
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>
{% endblock content %}

django/05_django/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
	<h1>SIGNUP</h1>
	<form action="{% url 'accounts:signup' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit">
	</form>
{% endblock content %}

django/05_django/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
	<h1>회원정보수정</h1>
	<form action="{% url 'accounts:update' %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>
{% endblock content %}