django/self/self_study3/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>/', views.hello, name='hello'),
]

django/self/self_study3/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django/self/self_study3/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

django/self/self_study3/articles/views.py
import random
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def greeting(request):
    foods = ['apple', 'banana', 'coconut',]
    info = {
        'name': 'Alice'
    }
    context = {
        'foods': foods,
        'info': info,
    }
    return render(request, 'greeting.html', context)

def dinner(request):
    foods = ['족발', '햄버거', '치킨', '초밥',]
    pick = random.choice(foods)
    context = {
        'pick': pick,
        'foods': foods,
    }
    return render(request, 'dinner.html', context)

def throw(request):
    return render(request, 'throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'catch.html', context)

def hello(request, name):
    context = {
        'name' : name,
    }
    return render(request, 'hello.html', context)

django/self/self_study3/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

django/self/self_study3/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
<h1>Catch</h1>
<h2>여기서 {{ message }}를 받았어!!</h2>
<a href="{% url 'articles:throw' %}">다시 던지러</a>
{% endblock content %}

django/self/self_study3/articles/templates/articles/dinner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{ pick }}은 {{ pick|length }}글자</p>
    <p>{{ foods|join:", "}}</p>

    <p>메뉴판</p>
    <ul>
        {% for food in foods %}
            <li>{{ food }}</li>
        {% endfor %}    
    </ul>
    
    <a href={% url 'articles:index' %}>뒤로</a>
</body>
</html>

django/self/self_study3/articles/templates/articles/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>저는 {{ foods.0 }}을 가장 좋아합니다.</p>
    <p>안녕하세요 저는 {{ info.name }} 입니다.</p>
    
    <a href={% url 'articles:index' %}>뒤로</a>
</body>
</html>

django/self/self_study3/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
    <h1>만나서 반가워요 {{ name }}님!</h1>
{% endblock content %}

django/self/self_study3/articles/templates/articles/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
	{% block content %}
	<h1>만나서 반가워요!</h1>
		<a href="{% url 'articles:greeting' %}">greeting</a>
		<a href="{% url 'articles:dinner' %}">dinner</a>
		<a href="{% url 'articles:throw' %}">throw</a>

		<a href="{% url 'pages:index' %}">두번째 앱의 index로 이동</a>
	{% endblock content %}
</body>
</html>

django/self/self_study3/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
    <h1>Throw</h1>
		<form action="{% url 'articles:catch' %}" method="GET">
			<label for="message">Throw</label>
			<input type="text" id="message" name="message">
			<input type="submit">
		</form>

		<a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}