django/self/self_study5/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
 path('login/', views.login, name='login'),
 path('logout/', views.logout, name='logout'),
 path('signup/', views.signup, name='signup'),
 path('delete/', views.delete, name='delete'),
 path('update/', views.update, name='update'),
 path('password/', views.change_password, name='change_password'),
]

django/self/self_study5/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/self/self_study5/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		{% if request.user.is_authenticated %}
		<h3>Hello, {{ user }}</h3>
		<form action="{% url 'accounts:logout' %}" method="POST">
			{% csrf_token %}
			<input type="submit" value="Logout">
		</form>
		<a href="{% url 'accounts:update' %}">회원정보 수정</a>
		<form action="{% url 'accounts:delete' %}" method="POST">
			{% csrf_token %}
			<input type="submit" value="회원탈퇴">
		</form>
		{% else %}
		<a href="{% url 'accounts:login' %}">Login</a>
		<a href="{% url 'accounts:signup' %}">Signup</a>
		{% endif %}
		{% block content %}
		{% endblock content %}
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>