일별/1013/N_1(완성본)/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name="signup"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
]

일별/1013/N_1(완성본)/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

일별/1013/N_1(완성본)/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

일별/1013/N_1(완성본)/articles/models.py
from django.db import models
from django.conf import settings # 직접 가져오지 않고 ... settings 에서 가져온다

# User <-> ARticle 간의 DB API
''' 
1. 게시글을 작성한 유저 -> N : 1
    - article.user
    유저가 작성한 게시글들(역참조) -> 1 : N
    - user.article_set


2.  게시글을 좋아한 유저 -> N : M
    - article.like_users
    유저가 좋아요한 게시글들(역참조) -> N : M
    - user.like_articles
'''

class Article(models.Model):
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articels')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # comment_set 
    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments') # article_id
    # 1. 참조할 테이블(객체/모델) 이름 
    # 2. on_delete = 
        # models.CASCADE
        # NO_USER_NAME <- SET_DEAFULT
    # 3. related_name = 
        # 나를 참조하는 테이블(객체/모델)에서 조회할때 나오는 이름
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

일별/1013/N_1(완성본)/articles/forms.py
from django import forms 
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label = "Title",
        widget = forms.TextInput(
            attrs={
            #    'class' :  'my-title',
                'placeholder' : '입력해주세요 제목을',
                'maxlength': 10,
            }
        ),
        error_messages = {
            'required': 'give me title!'
        },
    )

    content = forms.CharField(
        label = "Content",
        widget = forms.Textarea(
            attrs={
                # 'class' : 'my-content',
                'placeholder' : '입력해주세요! 콘텐츠를',
                'rows': 4,
            }
        ),
        error_messages = {
            'required': 'give me content!'
        },
    )
 
    class Meta:
        model = Article
        # fields = '__all__'
        # exclude = ('user',)
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = ['content']
            # fields -> '__all__' or list()
        
        exclude = ('article', 'user',)
            # exclude -> 반드시 tuple ex. ('article',)

일별/1013/N_1(완성본)/articles/views.py
import re
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.views.decorators.http import require_POST


# Create your views here.
def index(request):
    # DB에 전체 데이터를 조회
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def create(request):
    form = ArticleForm()
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    
    context = {
        'form': form,
    } 
    return render(request, 'articles/create.html', context)
    


def detail(request, pk):
    # variable routing으로 받은 pk 값으로 데이터를 조회
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm() # 댓글을 달기 위한
    comments = article.comments.all() 
        # 1. 댓글을 보여주기 위한 
        # 2. 역참조한거다! 
    context = {
        'article': article,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user.is_authenticated: # 로그인 했니?
        if request.user == article.user: # 작성자와 로그인 유저가 똑같아?    
            article.delete()
            return redirect('articles:index')
    return redirect('articles:detial', article.pk)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(data=request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')        
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        # 데이터 받을 판을 만들어주는거 (form)
        comment_form = CommentForm(request.POST)
        article = Article.objects.get(pk=pk) # article_pk

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save() # NOT NULL CONSTRAINS ??? article_id..?
    
    return redirect('articles:detail', article.pk) 

# 기존 방식은 맞음
# def comments_delete(request,  comment_pk):
#     comment = Comment.objects.get(pk=comment_pk)
#     article_pk = comment.article.pk
#     comment.delete()
#     return redirect('articles:detail', article_pk)


# REST API를 위해서 url의 일관성 지키자!
@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


def likes(request, article_pk):
    if request.user.is_authenticated:
        # 1. article 정보가 필요 <- article_pk
        article = get_object_or_404(Article, pk=article_pk)

        # 2. 게시글을 이미 좋아하고 있다 -> 좋아요 취소
        # if article.like_users.filter(pk=request.user.pk).exists():
        if request.user in article.like_users.all():
            article.like_users.remove(request.user)
        # 3. 게시글을 좋아하지 않았다. -> 좋아요 승인
        else:
            article.like_users.add(request.user)
        return redirect('articles:index')

    return redirect('accounts:login')

일별/1013/N_1(완성본)/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-success" value="submit">create</button>
    {% endbuttons %}
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

일별/1013/N_1(완성본)/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h2>{{ article.pk }}번째 글입니다.</h2>
  <hr>
  <p>작성자 : {{ article.user }}</p>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  {% if article.user == request.user %}
    <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE">
    </form>
  {% endif %}
  <hr>
  <h4>댓글 목록</h4>
  {% if rquest.user.is_authenticated %}
    {% if comments|length != 0  %}
      <h5>{{ comments|length }}개의 댓글이 있습니다.</h5>
    {% endif %}

    {% comment %} 
      <h5>{{ article.comments.all|length }}</h5>
      <h5>{{ comments.count }}</h5>
      <h5>{{ article.comments.count }}</h5> 
    {% endcomment %}
    <ul>
      {% for comment in comments %}
      <li>
        {{ comment.user }}: {{ comment.content }} - {{ comment.updated_at }}
        {% if comment.user == request.user %}
          <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>  
        {% endif %}
      </li>
      {% empty %}
        <li>
          <p>댓글이 없어요...</p>
        </li>
      {% endfor %}
    </ul>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value="COMMENT-CREATE">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <hr>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock content %}

일별/1013/N_1(완성본)/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">create</a>
  <hr>
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }}</p>
    <p>작성자 : {{ article.user }}</p>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <form action="{% url 'articles:likes' article.pk %}" method="POST">
      {% csrf_token %}
      {% if user in article.like_users.all %}
      <button>
        <i class="fa-sharp fa-solid fa-heart"></i>
      </button>
      {% else %}
      <button>
        <i class="fa-regular fa-heart"></i>
      </button>
      {% endif %}
    </form>
    <a href="{% url 'articles:detail' article.pk %}">상세 페이지</a>
    <hr>
  {% endfor %}
{% endblock content %}

일별/1013/N_1(완성본)/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-success" value="submit">update</button>
    {% endbuttons %}
  </form>
  <hr>
  <a href="{% url 'articles:detail' article.pk %}">뒤로가기</a>
{% endblock content %}